// Dedicated, hand-crafted Asset Allocation Report template — same
// architecture as goalReportHtml.js (see that file for the full
// rationale): fully self-contained, inline-styled HTML built directly
// from data, no Tailwind, no DOM cloning, explicit page breaks computed
// here rather than left to the browser to figure out.
import { fmtINR, fmtFull, fmtDate } from './calc';
import {
  normalizeAllocation, allocationTotals, groupComposition, sectionGroupColumns, fmtPct, SECTION_COLORS,
} from './assets';
import { LOGO_BASE64 } from './branding';

const PAGE_W = 660;
const PAGE_MIN_H = 990;

const SECTION_META = {
  financial: { title: 'Financial Assets', icon: '📈', accent: '#4f46e5', bg: '#eef2ff', border: '#c7d2fe' },
  physical: { title: 'Physical Assets', icon: '🏠', accent: '#b45309', bg: '#fffbeb', border: '#fde68a' },
  liabilities: { title: 'Loans & Liabilities', icon: '💳', accent: '#be123c', bg: '#fff1f2', border: '#fecdd3' },
};

function letterheadHtml(dateStr) {
  return `
  <div style="background:linear-gradient(135deg,#0f1f3d 0%,#1044a3 100%);color:white;padding:18px 24px;border-radius:12px;margin-bottom:22px;display:flex;align-items:center;justify-content:space-between;gap:12px;">
    <div style="display:flex;align-items:center;gap:12px;">
      <img src="${LOGO_BASE64}" style="width:36px;height:36px;object-fit:contain;border-radius:8px;background:rgba(255,255,255,0.15);padding:3px;" />
      <div>
        <div style="font-size:13px;font-weight:700;">Team Fintness</div>
        <div style="font-size:9px;opacity:0.6;letter-spacing:0.5px;margin-top:1px;">Let's Build a Fitter Financial Future Together</div>
      </div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:9px;font-weight:800;letter-spacing:1.5px;opacity:0.95;">ASSET ALLOCATION REPORT</div>
      <div style="font-size:9px;font-weight:700;opacity:0.85;margin-top:1px;">${dateStr}</div>
    </div>
  </div>`;
}

function footerHtml(pageNum, totalPages) {
  return `
  <div style="margin-top:auto;padding-top:10px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;font-size:8px;color:#94a3b8;">
    <span>Generated by Team Fintness Customer Relationship Management System</span>
    <span>Confidential &nbsp;·&nbsp; Page ${pageNum} of ${totalPages}</span>
  </div>`;
}

function pageOpen() {
  return `<div style="width:${PAGE_W}px;min-height:${PAGE_MIN_H}px;margin:0 auto;display:flex;flex-direction:column;break-after:page;page-break-after:always;font-family:'DM Sans',system-ui,sans-serif;color:#1e293b;">`;
}
const pageClose = () => `</div>`;

function kpiTile({ label, value, caption, accent, bg }) {
  return `
  <div style="flex:1;background:${bg};border:1px solid ${accent}22;border-radius:12px;padding:14px 16px;">
    <div style="font-size:8.5px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:${accent};opacity:0.85;">${label}</div>
    <div style="font-size:17px;font-weight:800;color:#0f172a;margin-top:6px;letter-spacing:-0.3px;">${value}</div>
    ${caption ? `<div style="font-size:8.5px;color:#94a3b8;margin-top:3px;">${caption}</div>` : ''}
  </div>`;
}

// CSS conic-gradient donut — no SVG arc math needed, and Chrome (what these
// reports print through) supports it natively.
function buildConicGradient(data, gross) {
  let cursor = 0;
  const stops = data.map(d => {
    const pct = gross > 0 ? (d.value / gross) * 100 : 0;
    const start = cursor;
    cursor += pct;
    return `${d.color} ${start}% ${cursor}%`;
  });
  return `conic-gradient(${stops.join(', ')})`;
}

function buildOverviewPage(client, alloc, t, dateStr, pageNum, totalPages) {
  const data = [
    { name: 'Financial Assets', value: t.financial, color: SECTION_COLORS.financial },
    { name: 'Physical Assets', value: t.physical, color: SECTION_COLORS.physical },
    { name: 'Liabilities', value: t.liabilities, color: SECTION_COLORS.liabilities },
  ].filter(d => d.value > 0);
  const gross = t.financial + t.physical + t.liabilities;
  const gradient = data.length > 0 ? buildConicGradient(data, gross) : '#e2e8f0';

  const legendRows = data.map(d => `
    <div style="margin-bottom:12px;">
      <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:5px;">
        <div style="display:flex;align-items:center;gap:7px;">
          <span style="width:9px;height:9px;border-radius:2px;background:${d.color};display:inline-block;"></span>
          <span style="font-size:11px;font-weight:600;color:#334155;">${d.name}</span>
        </div>
        <div style="display:flex;align-items:center;gap:10px;">
          <span style="font-size:11px;font-weight:700;color:#0f172a;">${fmtINR(d.value)}</span>
          <span style="font-size:10px;font-weight:700;color:${d.color};width:38px;text-align:right;display:inline-block;">${fmtPct(d.value, gross)}</span>
        </div>
      </div>
      <div style="height:5px;border-radius:99px;background:#f1f5f9;overflow:hidden;">
        <div style="width:${Math.max(1, gross > 0 ? (d.value / gross) * 100 : 0)}%;height:100%;background:${d.color};border-radius:99px;"></div>
      </div>
    </div>`).join('');

  return `${pageOpen()}
    ${letterheadHtml(dateStr)}
    <div style="font-family:'Playfair Display',serif;font-size:26px;font-weight:700;color:#0f172a;letter-spacing:-0.5px;">Asset Allocation Report</div>
    <div style="font-size:14px;font-weight:600;color:#475569;margin-top:7px;padding-bottom:16px;border-bottom:1px solid #e2e8f0;">${client.name} &nbsp;·&nbsp; ${client.pan || '—'}${alloc.updatedAt ? ` &nbsp;·&nbsp; Updated ${fmtDate(alloc.updatedAt)}` : ''}</div>

    <div style="font-size:14px;font-weight:700;color:#0f172a;margin-top:22px;margin-bottom:12px;">Net worth summary</div>
    <div style="display:flex;gap:10px;">
      ${kpiTile({ label: 'Net Worth', value: fmtFull(t.netWorth), caption: 'Total assets minus liabilities', accent: '#4338ca', bg: '#eef2ff' })}
      ${kpiTile({ label: 'Total Assets', value: fmtINR(t.totalAssets), caption: 'Financial + physical holdings', accent: '#047857', bg: '#ecfdf5' })}
      ${kpiTile({ label: 'Loans & Liabilities', value: fmtINR(t.liabilities), caption: t.liabilities > 0 ? 'Outstanding across all loans' : 'Debt-free', accent: '#be123c', bg: '#fff1f2' })}
    </div>

    <div style="font-size:14px;font-weight:700;color:#0f172a;margin-top:26px;margin-bottom:14px;">Net worth composition</div>
    <div style="border:1px solid #e2e8f0;border-radius:14px;padding:20px 22px;display:flex;align-items:center;gap:26px;">
      <div style="position:relative;width:132px;height:132px;flex-shrink:0;">
        <div style="width:132px;height:132px;border-radius:50%;background:${gradient};"></div>
        <div style="position:absolute;top:16px;left:16px;width:100px;height:100px;border-radius:50%;background:white;display:flex;flex-direction:column;align-items:center;justify-content:center;">
          <div style="font-size:8px;font-weight:700;letter-spacing:0.5px;text-transform:uppercase;color:#94a3b8;">Net Worth</div>
          <div style="font-size:12px;font-weight:800;color:${t.netWorth < 0 ? '#dc2626' : '#0f172a'};margin-top:3px;">${fmtINR(t.netWorth)}</div>
        </div>
      </div>
      <div style="flex:1;min-width:0;">${legendRows || '<div style="font-size:11px;color:#94a3b8;font-style:italic;">No values recorded yet.</div>'}${alloc.peRatio ? `
      <div style="margin-top:6px;padding-top:12px;border-top:1px solid #f1f5f9;display:inline-block;">
        <div style="font-size:8px;font-weight:700;letter-spacing:0.5px;text-transform:uppercase;color:#94a3b8;">P/E Ratio</div>
        <div style="font-size:12px;font-weight:800;color:#4338ca;margin-top:2px;">${alloc.peRatio}x</div>
      </div>` : ''}</div>
    </div>

    <div style="font-size:14px;font-weight:700;color:#0f172a;margin-top:26px;margin-bottom:12px;">Asset &amp; liability composition</div>
    <div style="border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
      <table style="width:100%;border-collapse:collapse;">
        <thead>
          <tr style="background:#0f1f3d;">
            <th style="text-align:left;padding:9px 14px;font-size:9px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:white;">Asset / Liability Class</th>
            <th style="text-align:right;padding:9px 14px;font-size:9px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:white;white-space:nowrap;">Amount</th>
            <th style="text-align:right;padding:9px 14px;font-size:9px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:white;white-space:nowrap;">% of Section</th>
          </tr>
        </thead>
        <tbody>
          ${compositionTableRows(alloc, t)}
        </tbody>
      </table>
    </div>

    ${footerHtml(pageNum, totalPages)}
  ${pageClose()}`;
}

// Single consolidated table (like the Goal Report's Goal Funding Status
// table) instead of a separate card per section — but still visually
// bifurcated via a colored, section-labelled divider row ahead of each
// section's own classes, so Financial/Physical/Liabilities read as
// distinct blocks within the one table rather than one flat list.
function compositionTableRows(alloc, t) {
  return ['financial', 'physical', 'liabilities'].map(sectionId => {
    const meta = SECTION_META[sectionId];
    const rows = groupComposition(alloc, sectionId);
    const total = t[sectionId];

    const subheader = `
    <tr style="background:${meta.bg};">
      <td colspan="3" style="padding:7px 14px;">
        <div style="display:flex;align-items:center;justify-content:space-between;">
          <div style="display:flex;align-items:center;gap:6px;">
            <span style="font-size:12px;">${meta.icon}</span>
            <span style="font-size:10.5px;font-weight:800;color:${meta.accent};letter-spacing:0.3px;">${meta.title}</span>
          </div>
          <span style="font-size:10.5px;font-weight:800;color:${meta.accent};">${fmtINR(total)}</span>
        </div>
      </td>
    </tr>`;

    const emptyText = sectionId === 'liabilities' ? 'Debt-free — no liabilities recorded.' : 'No holdings recorded yet.';
    const classRows = rows.length > 0 ? rows.map(r => `
    <tr style="border-top:1px solid #f1f5f9;">
      <td style="padding:7px 14px 7px 32px;font-size:10.5px;font-weight:500;color:#334155;">
        <span style="display:inline-block;width:7px;height:7px;border-radius:2px;background:${r.color};margin-right:8px;"></span>${r.label}
      </td>
      <td style="padding:7px 14px;text-align:right;font-size:10.5px;font-weight:700;color:#0f172a;white-space:nowrap;">${fmtINR(r.amount)}</td>
      <td style="padding:7px 14px;text-align:right;font-size:10px;font-weight:700;color:${r.color};white-space:nowrap;">${fmtPct(r.amount, total)}</td>
    </tr>`).join('') : `
    <tr style="border-top:1px solid #f1f5f9;"><td colspan="3" style="padding:7px 14px 7px 32px;font-size:10px;color:#94a3b8;font-style:italic;">${emptyText}</td></tr>`;

    return subheader + classRows;
  }).join('');
}

function holdingCard(col, sectionId) {
  const meta = SECTION_META[sectionId];
  const rows = col.items.map(it => {
    const pct = col.total > 0 ? (it.amount / col.total) * 100 : 0;
    return `
    <div style="margin-bottom:11px;">
      <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:4px;">
        <span style="font-size:10.5px;font-weight:600;color:#334155;">${it.label}${it.isCustom ? ' <span style="font-size:7.5px;font-weight:700;letter-spacing:0.3px;text-transform:uppercase;color:#94a3b8;background:#f1f5f9;padding:1px 5px;border-radius:4px;">custom</span>' : ''}</span>
        <span style="font-size:10.5px;font-weight:700;color:#0f172a;">${fmtINR(it.amount)} <span style="font-size:9px;font-weight:600;color:#94a3b8;">${fmtPct(it.amount, col.total)}</span></span>
      </div>
      <div style="height:6px;border-radius:99px;background:#f1f5f9;overflow:hidden;">
        <div style="width:${Math.max(2, pct)}%;height:100%;background:${it.color};border-radius:99px;"></div>
      </div>
    </div>`;
  }).join('');

  return `
  <div style="background:${meta.bg};border:1px solid ${meta.border};border-radius:16px;padding:24px 26px;margin-bottom:26px;break-inside:avoid;page-break-inside:avoid;">
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:18px;">
      <div style="display:flex;align-items:center;gap:10px;">
        <div style="width:34px;height:34px;border-radius:10px;background:white;display:flex;align-items:center;justify-content:center;font-size:16px;flex-shrink:0;">${meta.icon}</div>
        <div>
          <div style="font-size:14px;font-weight:800;color:#0f172a;">${col.title}</div>
          <div style="font-size:9.5px;font-weight:600;color:#94a3b8;margin-top:1px;">${meta.title} &nbsp;·&nbsp; ${fmtINR(col.total)}</div>
        </div>
      </div>
      <span style="font-size:10px;font-weight:800;color:${meta.accent};background:white;padding:4px 10px;border-radius:99px;">100%</span>
    </div>
    ${rows}
  </div>`;
}

function sectionHeadingHtml(sectionId, isFirstOnPage) {
  const meta = SECTION_META[sectionId];
  return `
  <div style="display:flex;align-items:center;gap:8px;margin-bottom:13px;${isFirstOnPage ? '' : 'margin-top:6px;'}">
    <div style="width:24px;height:24px;border-radius:7px;background:${meta.bg};border:1px solid ${meta.border};display:flex;align-items:center;justify-content:center;font-size:12px;flex-shrink:0;">${meta.icon}</div>
    <div style="font-size:11.5px;font-weight:800;letter-spacing:0.4px;text-transform:uppercase;color:${meta.accent};">${meta.title}</div>
  </div>`;
}

function buildDetailPage(chunk, dateStr, pageNum, totalPages) {
  let lastSection = null;
  const cards = chunk.map(({ col, sectionId }) => {
    const heading = sectionId !== lastSection ? sectionHeadingHtml(sectionId, lastSection === null) : '';
    lastSection = sectionId;
    return heading + holdingCard(col, sectionId);
  }).join('');
  return `${pageOpen()}
    ${letterheadHtml(dateStr)}
    <div style="font-family:'Playfair Display',serif;font-size:22px;font-weight:700;color:#0f172a;letter-spacing:-0.4px;">Allocation Details</div>
    <div style="font-size:10.5px;color:#64748b;margin-top:4px;margin-bottom:22px;">Every holding within its own asset class — each class treated as 100%</div>
    ${cards}
    ${footerHtml(pageNum, totalPages)}
  ${pageClose()}`;
}

function buildClosingPage(client, alloc, t, insightText, dateStr, pageNum, totalPages) {
  return `${pageOpen()}
    ${letterheadHtml(dateStr)}
    <div style="font-family:'Playfair Display',serif;font-size:22px;font-weight:700;color:#0f172a;letter-spacing:-0.4px;">Portfolio Insight &amp; Remarks</div>
    <div style="font-size:10.5px;color:#64748b;margin-top:4px;margin-bottom:22px;">Closing observations for ${client.name}'s portfolio</div>

    <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:14px;padding:18px 22px;margin-bottom:22px;">
      <div style="font-size:9px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:#64748b;margin-bottom:8px;">Portfolio Insight</div>
      <div style="font-size:11.5px;color:#334155;line-height:1.6;">${insightText}</div>
    </div>

    ${alloc.remark ? `
    <div style="font-size:12px;font-weight:700;color:#0f172a;margin-bottom:10px;">Advisor remark</div>
    <div style="background:white;border:1px solid #e2e8f0;border-left:3px solid #1044a3;border-radius:10px;padding:16px 18px;font-size:11px;color:#334155;line-height:1.6;white-space:pre-wrap;">${alloc.remark}</div>
    ` : ''}

    <div style="font-size:8.5px;color:#94a3b8;font-style:italic;margin-top:22px;">Important: Figures reflect holdings as recorded in the CRM as of the report date and may not include same-day market movements. Please reach out to your advisor for the latest valuations.</div>

    ${footerHtml(pageNum, totalPages)}
  ${pageClose()}`;
}

export function buildAssetReportHtml(client) {
  const alloc = normalizeAllocation(client.assetAllocation);
  const t = allocationTotals(alloc);
  const dateStr = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

  // One detail card per group-with-data, across all three sections, tagged
  // with its parent section for theming — flattened so pagination (2 per
  // page) doesn't need to know or care how many groups any one section has.
  const allCols = [];
  ['financial', 'physical', 'liabilities'].forEach(sectionId => {
    sectionGroupColumns(alloc, sectionId).filter(c => c.items.length > 0).forEach(col => {
      allCols.push({ col, sectionId });
    });
  });

  const detailPageCount = Math.max(0, Math.ceil(allCols.length / 2));
  const totalPages = 1 + detailPageCount + 1;

  // Auto-generated insight: equity/debt/commodity mix as a share of total
  // assets, plus the single largest holding across the whole portfolio.
  const assetMixParts = [];
  if (t.totalAssets > 0) {
    if (t.equity > 0) assetMixParts.push(`${fmtPct(t.equity, t.totalAssets)} equity`);
    if (t.debt > 0) assetMixParts.push(`${fmtPct(t.debt, t.totalAssets)} debt`);
    if (t.commodity > 0) assetMixParts.push(`${fmtPct(t.commodity, t.totalAssets)} commodity`);
  }
  const physicalShare = t.totalAssets > 0 && t.physical > 0 ? fmtPct(t.physical, t.totalAssets) : null;

  let largestHolding = null;
  allCols.forEach(({ col }) => {
    col.items.forEach(it => {
      if (!largestHolding || it.amount > largestHolding.amount) largestHolding = it;
    });
  });

  let insightText;
  if (t.totalAssets === 0) {
    insightText = 'No asset holdings have been recorded yet for this client — once allocation data is entered, this section will summarize the portfolio mix automatically.';
  } else {
    const mixSentence = assetMixParts.length > 0
      ? `Within financial holdings, the mix is currently ${assetMixParts.join(', ')}${physicalShare ? `, alongside physical assets making up ${physicalShare} of total assets` : ''}.`
      : (physicalShare ? `Physical assets make up ${physicalShare} of total assets.` : '');
    const largestSentence = largestHolding ? ` The single largest holding is <strong>${largestHolding.label}</strong> at ${fmtINR(largestHolding.amount)}.` : '';
    const debtNote = t.liabilities > 0 ? ` Outstanding liabilities of ${fmtINR(t.liabilities)} bring net worth to ${fmtINR(t.netWorth)}.` : ' This client carries no outstanding liabilities.';
    insightText = `${mixSentence}${largestSentence}${debtNote}`;
  }

  let pageNum = 1;
  let html = buildOverviewPage(client, alloc, t, dateStr, pageNum++, totalPages);

  for (let i = 0; i < allCols.length; i += 2) {
    html += buildDetailPage(allCols.slice(i, i + 2), dateStr, pageNum++, totalPages);
  }

  html += buildClosingPage(client, alloc, t, insightText, dateStr, pageNum++, totalPages);

  return html;
}
