// Dedicated, hand-crafted Policy Review Report template — same architecture
// as goalReportHtml.js / assetReportHtml.js (see goalReportHtml.js for the
// full rationale): fully self-contained, inline-styled HTML built directly
// from data, sized for an A4 portrait page from the start, with explicit
// page breaks computed here rather than left to the browser. Replaces the
// old approach of calling window.print() on the live on-screen calculator
// (visibility:hidden hacks, no letterhead/branding, and — the specific
// complaint that led to this file — the executive summary landing at the
// very end of the printout instead of the front).
import { LOGO_BASE64 } from './branding';

const PAGE_W = 660;
const PAGE_MIN_H = 990;

// Free-typed fields (client name, PAN, RM, policy name/no) go through raw
// template-literal interpolation below, unlike their on-screen React
// counterparts which JSX auto-escapes — so, unlike the read-only computed
// numbers around them, they need explicit escaping here.
function escHtml(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Full Indian comma-grouped rupee format (no L/Cr abbreviation) — matches
// the precision advisors already see on-screen in this tool, unlike the
// abbreviated fmtINR used by the Goal/Asset reports.
const inr = (n) => {
  if (n === null || n === undefined || isNaN(n)) return '—';
  const sign = n < 0 ? '-' : '';
  const abs = Math.abs(Math.round(n));
  const s = abs.toString();
  if (s.length <= 3) return sign + '₹' + s;
  const last3 = s.slice(-3);
  const rest = s.slice(0, -3).replace(/\B(?=(\d{2})+(?!\d))/g, ',');
  return sign + '₹' + rest + ',' + last3;
};

const pct = (n, d = 2) => (n === null || n === undefined || isNaN(n)) ? '—' : `${n.toFixed(d)}%`;

const irrHex = (v) => (v === null || isNaN(v)) ? '#64748b' : v >= 8 ? '#16a34a' : v >= 5 ? '#d97706' : '#dc2626';
const irrBg = (v) => (v === null || isNaN(v)) ? '#f1f5f9' : v >= 8 ? '#f0fdf4' : v >= 5 ? '#fffbeb' : '#fef2f2';

const CATEGORY_LABEL = { traditional: 'Traditional', ulip: 'ULIP' };
const SUBTYPE_LABEL = { endowment: 'Endowment', moneyback: 'Money Back', whole_life: 'Whole Life' };

const WINNER_COPY = {
  continue: { label: 'Continue Policy', emoji: '✅' },
  paidup: { label: 'Go Paid-up', emoji: '⏸️' },
  mf: { label: 'Mutual Fund is Better', emoji: '📈' },
};

const REC_COLOR = {
  continue: '#16a34a',
  mfbetter: '#16a34a',
  paidup: '#d97706',
  review: '#2563eb',
};

function letterheadHtml(dateStr) {
  return `
  <div style="background:linear-gradient(135deg,#0f1f3d 0%,#1044a3 100%);color:white;padding:18px 24px;border-radius:12px;margin-bottom:22px;display:flex;align-items:center;justify-content:space-between;gap:12px;">
    <div style="display:flex;align-items:center;gap:12px;">
      <img src="${LOGO_BASE64}" style="width:36px;height:36px;object-fit:contain;border-radius:8px;background:rgba(255,255,255,0.15);padding:3px;" />
      <div>
        <div style="font-size:13px;font-weight:700;">Team Fintness</div>
        <div style="font-size:9px;opacity:0.6;letter-spacing:0.5px;margin-top:1px;">Let's Build a Fitter Financial Future Together</div>
      </div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:9px;font-weight:800;letter-spacing:1.5px;opacity:0.95;">POLICY REVIEW REPORT</div>
      <div style="font-size:9px;font-weight:700;opacity:0.85;margin-top:1px;">${dateStr}</div>
    </div>
  </div>`;
}

function footerHtml(pageNum, totalPages) {
  return `
  <div style="margin-top:auto;padding-top:10px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;font-size:8px;color:#94a3b8;">
    <span>Generated by Team Fintness Customer Relationship Management System</span>
    <span>Confidential &nbsp;·&nbsp; Page ${pageNum} of ${totalPages}</span>
  </div>`;
}

function pageOpen() {
  return `<div style="width:${PAGE_W}px;min-height:${PAGE_MIN_H}px;margin:0 auto;display:flex;flex-direction:column;break-after:page;page-break-after:always;font-family:'DM Sans',system-ui,sans-serif;color:#1e293b;">`;
}
const pageClose = () => `</div>`;

function kpiTile({ label, value, caption, accent, bg }) {
  return `
  <div style="flex:1;background:${bg};border:1px solid ${accent}22;border-radius:12px;padding:14px 16px;">
    <div style="font-size:8.5px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:${accent};opacity:0.85;">${label}</div>
    <div style="font-size:17px;font-weight:800;color:#0f172a;margin-top:6px;letter-spacing:-0.3px;">${value}</div>
    ${caption ? `<div style="font-size:8.5px;color:#94a3b8;margin-top:3px;">${caption}</div>` : ''}
  </div>`;
}

function policyCategoryLabel(res) {
  const cat = CATEGORY_LABEL[res.policyCategory] || res.policyCategory;
  if (res.isUlip) return cat;
  const sub = SUBTYPE_LABEL[res.policySubtype] || res.policySubtype;
  return sub ? `${cat} · ${sub}` : cat;
}

function buildOverviewPage(data, results, dateStr, pageNum, totalPages) {
  const totalPremium = results.reduce((s, r) => s + (r.annualPremium || 0), 0);
  const totalRecommended = results.reduce((s, r) => s + (r.winner?.value || 0), 0);
  const totalUpside = results.reduce((s, r) => s + Math.max(0, (r.winner?.value || 0) - (r.continueVal || 0)), 0);

  const counts = results.reduce((acc, r) => {
    const t = r.winner?.type || 'continue';
    acc[t] = (acc[t] || 0) + 1;
    return acc;
  }, {});
  const parts = [];
  if (counts.mf) parts.push(`<strong>${counts.mf}</strong> recommend migrating to mutual funds`);
  if (counts.paidup) parts.push(`<strong>${counts.paidup}</strong> recommend going paid-up`);
  if (counts.continue) parts.push(`<strong>${counts.continue}</strong> are best left running as-is`);
  let focusText;
  if (results.length === 0) {
    focusText = 'No policies have been analysed yet.';
  } else if (results.length === 1) {
    const only = results[0];
    focusText = `The single policy reviewed points to <strong>${WINNER_COPY[only.winner.type]?.label || only.winner.name}</strong> as the stronger path forward.`;
  } else {
    focusText = `Of the ${results.length} policies reviewed, ${parts.join(', ')}.`;
  }

  const rows = results.map((r) => {
    const wc = WINNER_COPY[r.winner?.type] || { label: r.winner?.name || '—', emoji: '💡' };
    const upside = Math.max(0, (r.winner?.value || 0) - (r.continueVal || 0));
    return `
    <tr>
      <td style="padding:11px 14px;border-bottom:1px solid #f1f5f9;font-weight:700;color:#0f172a;font-size:11px;">${escHtml(r.policyName) || `Policy #${r.policyId}`}${r.policyNo ? ` <span style="font-weight:500;color:#64748b;font-size:9.5px;">(${escHtml(r.policyNo)})</span>` : ''}</td>
      <td style="padding:11px 14px;border-bottom:1px solid #f1f5f9;font-size:10.5px;color:#475569;">${policyCategoryLabel(r)}</td>
      <td style="padding:11px 14px;border-bottom:1px solid #f1f5f9;font-size:10.5px;font-weight:700;color:${REC_COLOR[r.recType] || '#2563eb'};">${wc.emoji} ${wc.label}</td>
      <td style="padding:11px 14px;border-bottom:1px solid #f1f5f9;text-align:right;font-size:10.5px;font-weight:700;color:#0f172a;">${inr(r.winner?.value)}</td>
      <td style="padding:11px 14px;border-bottom:1px solid #f1f5f9;text-align:right;font-size:10.5px;font-weight:700;color:${upside > 0 ? '#16a34a' : '#94a3b8'};">${upside > 0 ? '+' + inr(upside) : '—'}</td>
    </tr>`;
  }).join('');

  return `${pageOpen()}
    ${letterheadHtml(dateStr)}
    <div style="font-family:'Playfair Display',serif;font-size:26px;font-weight:700;color:#0f172a;letter-spacing:-0.5px;">Policy Review Report</div>
    <div style="font-size:14px;font-weight:600;color:#475569;margin-top:7px;padding-bottom:16px;border-bottom:1px solid #e2e8f0;">${escHtml(data.clientName) || 'Client'} &nbsp;·&nbsp; ${escHtml(data.clientPan) || '—'}${data.groupLeader ? ` &nbsp;·&nbsp; RM: ${escHtml(data.groupLeader)}` : ''}</div>

    <div style="font-size:14px;font-weight:700;color:#0f172a;margin-top:22px;margin-bottom:12px;">Portfolio review at a glance</div>
    <div style="display:flex;gap:10px;">
      ${kpiTile({ label: 'Policies Reviewed', value: String(results.length), caption: 'Life insurance policies analysed', accent: '#4338ca', bg: '#eef2ff' })}
      ${kpiTile({ label: 'Total Annual Premium', value: inr(totalPremium), caption: 'Combined yearly outflow', accent: '#1d4ed8', bg: '#eff6ff' })}
      ${kpiTile({ label: 'Recommended Path Value', value: inr(totalRecommended), caption: 'If every recommendation is followed', accent: '#047857', bg: '#ecfdf5' })}
      ${kpiTile({ label: 'Additional Wealth Potential', value: inr(totalUpside), caption: 'Upside vs. simply continuing', accent: '#c2410c', bg: '#fff7ed' })}
    </div>

    <div style="font-size:14px;font-weight:700;color:#0f172a;margin-top:26px;margin-bottom:12px;">Executive summary</div>
    <div style="border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
      <table style="width:100%;border-collapse:collapse;">
        <thead>
          <tr style="background:#0f1f3d;">
            <th style="text-align:left;padding:10px 14px;font-size:9px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:white;">Policy</th>
            <th style="text-align:left;padding:10px 14px;font-size:9px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:white;">Category</th>
            <th style="text-align:left;padding:10px 14px;font-size:9px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:white;">Recommended Path</th>
            <th style="text-align:right;padding:10px 14px;font-size:9px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:white;">Projected Value</th>
            <th style="text-align:right;padding:10px 14px;font-size:9px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:white;">vs. Continuing</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    </div>

    <div style="margin-top:16px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:14px 18px;">
      <div style="font-size:9px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:#64748b;">Review Focus</div>
      <div style="font-size:11px;color:#334155;margin-top:5px;line-height:1.5;">${focusText}</div>
    </div>

    ${footerHtml(pageNum, totalPages)}
  ${pageClose()}`;
}

// Horizontal comparison bar for one scenario row — same visual language as
// the Asset Report's composition bars (legendRows in assetReportHtml.js).
function scenarioBar({ label, value, color, irrTag, isWinner, maxValue }) {
  const widthPct = maxValue > 0 ? Math.max(2, (Math.max(0, value) / maxValue) * 100) : 2;
  return `
  <div style="margin-bottom:12px;${isWinner ? `background:${color}0d;border:1px solid ${color}33;border-radius:9px;padding:8px 10px;margin-left:-10px;margin-right:-10px;` : ''}">
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:5px;">
      <div style="display:flex;align-items:center;gap:7px;">
        <span style="width:9px;height:9px;border-radius:2px;background:${color};display:inline-block;flex-shrink:0;"></span>
        <span style="font-size:11px;font-weight:${isWinner ? '800' : '600'};color:#334155;">${label}${isWinner ? ' <span style="font-size:8px;font-weight:800;letter-spacing:0.4px;text-transform:uppercase;color:' + color + ';background:' + color + '1a;padding:1px 6px;border-radius:99px;margin-left:6px;">Recommended</span>' : ''}</span>
      </div>
      <div style="display:flex;align-items:center;gap:10px;">
        <span style="font-size:11px;font-weight:700;color:#0f172a;font-family:'IBM Plex Mono',monospace;">${inr(value)}</span>
        ${irrTag}
      </div>
    </div>
    <div style="height:6px;border-radius:99px;background:#f1f5f9;overflow:hidden;">
      <div style="width:${widthPct}%;height:100%;background:${color};border-radius:99px;"></div>
    </div>
  </div>`;
}

function irrPillHtml(v) {
  return `<span style="font-size:9px;font-weight:700;font-family:'IBM Plex Mono',monospace;color:${irrHex(v)};background:${irrBg(v)};border:1px solid ${irrHex(v)}33;padding:2px 7px;border-radius:99px;width:44px;text-align:center;display:inline-block;">${pct(v)}</span>`;
}

function ulipChargesHtml(res) {
  if (!res.isUlip || !Array.isArray(res.ulipCharges) || res.ulipCharges.length === 0) return '';
  const maxC = Math.max(...res.ulipCharges.map(c => c.val), 0.01);
  const rows = res.ulipCharges.map((ch) => `
    <div style="display:flex;align-items:center;gap:10px;margin-bottom:7px;">
      <span style="font-size:9.5px;color:#475569;width:130px;flex-shrink:0;">${escHtml(ch.name)}</span>
      <div style="flex:1;height:6px;background:#f1f5f9;border-radius:3px;overflow:hidden;">
        <div style="width:${Math.min(100, (ch.val / maxC) * 100)}%;height:100%;background:linear-gradient(to right,#dc2626,#fca5a5);border-radius:3px;"></div>
      </div>
      <span style="font-size:9.5px;font-weight:700;color:#475569;width:36px;text-align:right;">${pct(ch.val)}</span>
    </div>`).join('');

  return `
  <div style="margin-top:16px;background:#fef2f2;border:1px solid #fecdd3;border-radius:12px;padding:14px 16px;">
    <div style="font-size:10px;font-weight:800;letter-spacing:0.4px;text-transform:uppercase;color:#be123c;margin-bottom:10px;">ULIP Charges Breakdown &amp; Drag</div>
    <div style="display:flex;gap:10px;margin-bottom:12px;">
      ${kpiTile({ label: 'Total Charge Drag', value: pct(res.chargesDragTotal), accent: '#be123c', bg: 'white' })}
      ${kpiTile({ label: 'Estimated Net Return', value: pct(res.netReturnUlip), accent: '#0891b2', bg: 'white' })}
    </div>
    ${rows}
  </div>`;
}

function buildPolicyDetailPage(res, index, total, data, dateStr, pageNum, totalPages) {
  const maxScenarioValue = Math.max(res.continueVal || 0, res.paidUpVal || 0, res.surrenderVal || 0, res.mfFinalVal || 0, 1);
  const wc = WINNER_COPY[res.winner?.type] || { label: res.winner?.name || '—', emoji: res.recEmoji || '💡' };
  const completionPct = res.policyTerm > 0 ? (res.premiumsPaid / res.policyTerm) * 100 : 0;
  const mfTax = Math.max(0, res.mfFinalVal - (res.surrenderVal + res.annualPremium * Math.max(0, res.premiumTerm - res.premiumsPaid))) * ((data.ltcgRate ?? 12.5) / 100);

  const infoStat = (label, value) => `
    <div style="background:white;border:1px solid #e2e8f0;border-radius:9px;padding:11px 13px;">
      <div style="font-size:8px;font-weight:700;letter-spacing:0.5px;text-transform:uppercase;color:#94a3b8;">${label}</div>
      <div style="font-size:12.5px;font-weight:700;color:#0f172a;margin-top:4px;">${value}</div>
    </div>`;

  return `${pageOpen()}
    ${letterheadHtml(dateStr)}
    <div style="display:flex;align-items:flex-start;justify-content:space-between;gap:12px;">
      <div>
        <div style="font-family:'Playfair Display',serif;font-size:20px;font-weight:700;color:#0f172a;letter-spacing:-0.4px;">${escHtml(res.policyName) || `Policy #${res.policyId}`}${res.policyNo ? ` <span style="font-size:13px;font-weight:500;color:#64748b;">(${escHtml(res.policyNo)})</span>` : ''}</div>
        <div style="font-size:10.5px;color:#64748b;margin-top:3px;">${policyCategoryLabel(res)} &nbsp;·&nbsp; Policy ${index + 1} of ${total}</div>
      </div>
      <div style="text-align:right;flex-shrink:0;">
        <div style="font-size:8px;font-weight:700;letter-spacing:0.5px;text-transform:uppercase;color:#94a3b8;">Recommended</div>
        <div style="font-size:12px;font-weight:800;color:${REC_COLOR[res.recType] || '#2563eb'};margin-top:2px;">${wc.emoji} ${wc.label}</div>
      </div>
    </div>

    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:16px;">
      ${infoStat('Sum Assured', inr(res.sumAssured))}
      ${infoStat('Annual Premium', inr(res.annualPremium))}
      ${infoStat('Policy / Premium Term', `${res.policyTerm} / ${res.premiumTerm} yrs`)}
      ${infoStat('Term Completed', `${pct(completionPct, 0)} (Yr ${res.premiumsPaid})`)}
    </div>

    <div style="font-size:12px;font-weight:700;color:#0f172a;margin-top:22px;margin-bottom:12px;">Scenario comparison</div>
    <div style="border:1px solid #e2e8f0;border-radius:14px;padding:16px 18px 4px;">
      ${scenarioBar({ label: 'Continue Policy', value: res.continueVal, color: '#2563eb', isWinner: res.winner?.type === 'continue', maxValue: maxScenarioValue, irrTag: irrPillHtml(res.continueIRR) })}
      ${scenarioBar({ label: 'Go Paid-up', value: res.paidUpVal, color: '#d97706', isWinner: res.winner?.type === 'paidup', maxValue: maxScenarioValue, irrTag: irrPillHtml(res.paidUpIRR) })}
      ${scenarioBar({ label: 'Surrender Value (Today)', value: res.surrenderVal, color: '#94a3b8', isWinner: false, maxValue: maxScenarioValue, irrTag: irrPillHtml(res.surrenderIRR) })}
      ${scenarioBar({ label: 'Mutual Fund (Post-tax)', value: res.mfFinalVal, color: '#16a34a', isWinner: res.winner?.type === 'mf', maxValue: maxScenarioValue, irrTag: irrPillHtml(parseFloat(data.mfReturn)) })}
    </div>

    <div style="margin-top:16px;background:${(res.wealthGain ?? 0) >= 0 ? '#f0fdf4' : '#fef2f2'};border:1px solid ${(res.wealthGain ?? 0) >= 0 ? '#bbf7d0' : '#fecdd3'};border-radius:12px;padding:13px 16px;display:flex;align-items:center;justify-content:space-between;gap:12px;">
      <div style="font-size:10.5px;color:#334155;">
        ${(res.wealthGain ?? 0) >= 0 ? 'Mutual fund path generates more wealth than continuing the policy' : 'Policy generates more wealth than the mutual fund path in this case'}
        <div style="font-size:9px;color:#94a3b8;margin-top:2px;">${inr(res.mfFinalVal)} (MF) vs ${inr(res.continueVal)} (Policy) over ${res.yearsLeft} years</div>
      </div>
      <div style="font-size:15px;font-weight:800;color:${(res.wealthGain ?? 0) >= 0 ? '#16a34a' : '#dc2626'};white-space:nowrap;">${(res.wealthGain ?? 0) >= 0 ? '+' : ''}${inr(res.wealthGain)}</div>
    </div>

    <div style="margin-top:16px;background:${REC_COLOR[res.recType] || '#2563eb'}0d;border:1px solid ${REC_COLOR[res.recType] || '#2563eb'}33;border-radius:14px;padding:16px 18px;">
      <div style="display:flex;align-items:flex-start;gap:12px;">
        <div style="font-size:22px;flex-shrink:0;">${res.recEmoji || wc.emoji}</div>
        <div>
          <div style="font-family:'Playfair Display',serif;font-size:14.5px;font-weight:700;color:${REC_COLOR[res.recType] || '#2563eb'};">${escHtml(res.recTitle)}</div>
          <div style="font-size:10.5px;color:#334155;line-height:1.55;margin-top:5px;">${escHtml(res.recBody)}</div>
          ${Array.isArray(res.actionSteps) && res.actionSteps.length > 0 ? `
          <div style="font-size:8.5px;font-weight:700;letter-spacing:0.5px;text-transform:uppercase;color:#64748b;margin-top:12px;margin-bottom:6px;">Proposed Action Steps</div>
          <div>
            ${res.actionSteps.map(step => `<div style="font-size:10px;color:#334155;line-height:1.6;padding:2px 0;">${escHtml(step)}</div>`).join('')}
          </div>` : ''}
        </div>
      </div>
    </div>

    ${ulipChargesHtml(res)}

    ${mfTax > 0 ? `<div style="font-size:8.5px;color:#94a3b8;font-style:italic;margin-top:14px;">Estimated LTCG tax of ${inr(mfTax)} on mutual fund gains has already been deducted from the post-tax value shown above.</div>` : ''}

    ${footerHtml(pageNum, totalPages)}
  ${pageClose()}`;
}

function buildClosingPage(data, results, dateStr, pageNum, totalPages) {
  const hasTraditional = results.some(r => !r.isUlip);
  const hasUlip = results.some(r => r.isUlip);

  return `${pageOpen()}
    ${letterheadHtml(dateStr)}
    <div style="font-family:'Playfair Display',serif;font-size:22px;font-weight:700;color:#0f172a;letter-spacing:-0.4px;">Assumptions &amp; Methodology</div>
    <div style="font-size:10.5px;color:#64748b;margin-top:4px;margin-bottom:18px;">The parameters and calculation method used across this review</div>

    <div style="font-size:12px;font-weight:700;color:#0f172a;margin-bottom:10px;">Comparison assumptions</div>
    <div style="display:flex;gap:10px;margin-bottom:22px;">
      ${kpiTile({ label: 'Expected MF CAGR', value: pct(parseFloat(data.mfReturn)), caption: 'Assumed mutual fund return', accent: '#1d4ed8', bg: '#eff6ff' })}
      ${kpiTile({ label: 'Equity LTCG Tax Rate', value: pct(data.ltcgRate ?? parseFloat(data.ltcg)), caption: 'Applied on mutual fund gains only', accent: '#c2410c', bg: '#fff7ed' })}
    </div>

    <div style="font-size:12px;font-weight:700;color:#0f172a;margin-bottom:10px;">Methodology</div>
    <div style="display:flex;flex-direction:column;gap:8px;margin-bottom:8px;">
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-left:3px solid #1044a3;border-radius:8px;padding:11px 14px;">
        <div style="font-size:10.5px;color:#334155;line-height:1.55;">Every scenario's yield is computed as an XIRR (Newton-Raphson with a bisection fallback) over the actual premium cash flow timeline, so Continue, Paid-up and Mutual Fund figures are directly comparable on a like-for-like annualised basis.</div>
      </div>
      ${hasTraditional ? `
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-left:3px solid #1044a3;border-radius:8px;padding:11px 14px;">
        <div style="font-size:10.5px;color:#334155;line-height:1.55;">Traditional policy maturity and surrender values are projected from the reversionary/terminal bonus rate and guaranteed/special surrender value factors entered for each policy — actuals depend on the insurer's declared bonus in future years.</div>
      </div>` : ''}
      ${hasUlip ? `
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-left:3px solid #1044a3;border-radius:8px;padding:11px 14px;">
        <div style="font-size:10.5px;color:#334155;line-height:1.55;">ULIP projections net out mortality, fund management, premium allocation and admin charges from the assumed gross return before compounding the fund value forward — the "Estimated Net Return" figure on each ULIP's page is this drag-adjusted rate.</div>
      </div>` : ''}
    </div>

    <div style="margin-top:22px;background:#fffbeb;border:1px solid #fde68a;border-radius:12px;padding:14px 18px;">
      <div style="font-size:9px;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;color:#92400e;margin-bottom:6px;">Important Disclaimer</div>
      <div style="font-size:9.5px;color:#78350f;line-height:1.6;">This review is for advisor use in client discussions and is illustrative only, based on the inputs provided and the assumptions above. Actual policy bonuses, surrender values and mutual fund returns are not guaranteed and may vary. Please verify exact surrender values with the insurer and consult the policy document before acting on any recommendation in this report.</div>
    </div>

    ${footerHtml(pageNum, totalPages)}
  ${pageClose()}`;
}

export function buildPolicyReportHtml(data) {
  const results = Array.isArray(data.results) ? data.results : [];
  const dateStr = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  const totalPages = 1 + results.length + 1;

  let pageNum = 1;
  let html = buildOverviewPage(data, results, dateStr, pageNum++, totalPages);

  results.forEach((res, i) => {
    html += buildPolicyDetailPage(res, i, results.length, data, dateStr, pageNum++, totalPages);
  });

  html += buildClosingPage(data, results, dateStr, pageNum++, totalPages);

  return html;
}
