// Dedicated Portfolio Review Report template — same architecture and look as
// goalReportHtml.js / assetReportHtml.js / policyReportHtml.js (see
// goalReportHtml.js for the full rationale): self-contained, inline-styled
// HTML built from data, A4 portrait pages with the shared letterhead and a
// "Page X of Y" footer, page breaks decided here rather than by the browser.
// Replaces window.print() on the live dashboard (landscape, app styling,
// charts squeezed onto the page).
//
// Unlike the goal/asset reports, the amount of content here is open-ended (a
// family statement can carry 40+ schemes, 20+ SIPs, a dozen advisory notes),
// so content is packed onto pages by estimated height: a table that runs out
// of room continues on the next page under its own header, and a section
// title never ends up alone at the bottom of a page.
import { fmtINR } from './calc';
import { LOGO_BASE64 } from './branding';

const PAGE_W = 660;
const PAGE_MIN_H = 990;
// Height available for content between the letterhead and the footer. The
// estimates below err on the tall side, so a page ends a little early rather
// than spilling over its footer.
const BODY_BUDGET = 815;

const ASSET_COLORS = { Equity: '#2d8a6e', Debt: '#3d7abf', Gold: '#c9a84c' };
const PALETTE = ['#1a5c4a', '#3d7abf', '#6b4fa0', '#c9a84c', '#e05c45', '#2d8a6e', '#88b04b', '#e8912a', '#d4845a', '#5c9bd6'];
const BADGE = {
  eq: { fg: '#1a5c4a', bg: '#e8f3ef' },
  dt: { fg: '#2c5f95', bg: '#e8f0f9' },
  hy: { fg: '#5b3f8c', bg: '#f0ecf7' },
  go: { fg: '#8a6f1e', bg: '#faf3e0' },
};
const NOTE = {
  warn: { label: 'Warning', color: '#dc2626', bg: '#fef2f2' },
  info: { label: 'Insight', color: '#2563eb', bg: '#eff6ff' },
  ok: { label: 'Good', color: '#16a34a', bg: '#f0fdf4' },
};

// Statement data comes from AI extraction of an uploaded PDF and the notes
// are free-typed — escape everything that lands in the HTML.
function esc(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const num = (n) => (isFinite(n) ? Number(n) : 0);
const money = (n) => fmtINR(num(n));
const signedMoney = (n) => `${num(n) >= 0 ? '+' : '−'}${fmtINR(Math.abs(num(n)))}`;
const rupees = (n) => `₹${Math.round(num(n)).toLocaleString('en-IN')}`;
const pct = (n, d = 1) => `${num(n).toFixed(d)}%`;
const signedPct = (n, d = 1) => `${num(n) >= 0 ? '+' : '−'}${Math.abs(num(n)).toFixed(d)}%`;
const gainHex = (n) => (num(n) >= 0 ? '#16a34a' : '#dc2626');
const xirrHex = (n) => (num(n) >= 10 ? '#16a34a' : num(n) >= 0 ? '#475569' : '#dc2626');
const lines = (text, perLine) => Math.max(1, Math.ceil(String(text || '').length / perLine));

function letterheadHtml(dateStr) {
  return `
  <div style="background:linear-gradient(135deg,#0f1f3d 0%,#1044a3 100%);color:white;padding:18px 24px;border-radius:12px;margin-bottom:22px;display:flex;align-items:center;justify-content:space-between;gap:12px;">
    <div style="display:flex;align-items:center;gap:12px;">
      <img src="${LOGO_BASE64}" style="width:36px;height:36px;object-fit:contain;border-radius:8px;background:rgba(255,255,255,0.15);padding:3px;" />
      <div>
        <div style="font-size:13px;font-weight:700;">Team Fintness</div>
        <div style="font-size:9px;opacity:0.6;letter-spacing:0.5px;margin-top:1px;">Let's Build a Fitter Financial Future Together</div>
      </div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:9px;font-weight:800;letter-spacing:1.5px;opacity:0.95;">PORTFOLIO REVIEW REPORT</div>
      <div style="font-size:9px;font-weight:700;opacity:0.85;margin-top:1px;">${dateStr}</div>
    </div>
  </div>`;
}

function footerHtml(pageNum, totalPages) {
  return `
  <div style="margin-top:auto;padding-top:10px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;font-size:8px;color:#94a3b8;">
    <span>Generated by Team Fintness Customer Relationship Management System</span>
    <span>Confidential &nbsp;·&nbsp; Page ${pageNum} of ${totalPages}</span>
  </div>`;
}

function pageOpen() {
  return `<div style="width:${PAGE_W}px;min-height:${PAGE_MIN_H}px;margin:0 auto;display:flex;flex-direction:column;break-after:page;page-break-after:always;font-family:'DM Sans',system-ui,sans-serif;color:#1e293b;">`;
}
const pageClose = () => `</div>`;

function kpiTile({ label, value, caption, accent, bg }) {
  return `
  <div style="flex:1;min-width:0;background:${bg};border:1px solid ${accent}22;border-radius:12px;padding:13px 12px;">
    <div style="font-size:8px;font-weight:700;letter-spacing:0.7px;text-transform:uppercase;color:${accent};opacity:0.85;">${label}</div>
    <div style="font-size:15px;font-weight:800;color:#0f172a;margin-top:6px;letter-spacing:-0.3px;white-space:nowrap;">${value}</div>
    ${caption ? `<div style="font-size:8px;color:#94a3b8;margin-top:3px;line-height:1.35;">${caption}</div>` : ''}
  </div>`;
}

const subHeading = (text) => `<div style="font-size:14px;font-weight:700;color:#0f172a;margin-top:22px;margin-bottom:12px;">${text}</div>`;
const SUB_HEADING_H = 52;

// ── Tables ──────────────────────────────────────────────────────────────
const TH = 'padding:9px 10px;font-size:8.5px;font-weight:700;letter-spacing:0.7px;text-transform:uppercase;color:white;white-space:nowrap;';
const TD = 'padding:8px 10px;border-bottom:1px solid #f1f5f9;font-size:10px;color:#334155;vertical-align:middle;';
const TF = 'padding:9px 10px;font-size:10px;font-weight:800;color:#0f172a;background:#f8fafc;border-top:1px solid #e2e8f0;';
const TABLE_HEAD_H = 32;
const TABLE_FOOT_H = 34;

// A table item for the page packer: `cols` = [{ label, align, width }],
// `rows` = [{ html, h }] (pre-rendered <tr>s with their estimated height).
function tableItem({ title, cols, rows, foot, emptyText }) {
  const head = `<tr style="background:#0f1f3d;">${cols.map(c => `<th style="${TH}text-align:${c.align || 'left'};${c.width ? `width:${c.width};` : ''}">${c.label}</th>`).join('')}</tr>`;
  return {
    type: 'table',
    titleH: title ? SUB_HEADING_H : 0,
    headH: TABLE_HEAD_H,
    footH: foot ? TABLE_FOOT_H : 0,
    emptyH: 40,
    rows,
    render: ({ rowsHtml, withFoot, continued }) => `
    ${title ? subHeading(`${title}${continued ? ' <span style="font-size:10px;font-weight:600;color:#94a3b8;">(continued)</span>' : ''}`) : ''}
    <div data-table-frame style="border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
      <table style="width:100%;border-collapse:collapse;table-layout:fixed;">
        <thead>${head}</thead>
        <tbody>${rowsHtml || `<tr><td colspan="${cols.length}" style="${TD}text-align:center;color:#94a3b8;font-style:italic;padding:14px;">${emptyText || 'No data available.'}</td></tr>`}</tbody>
        ${withFoot && foot ? `<tfoot>${foot}</tfoot>` : ''}
      </table>
    </div>`,
  };
}

const block = (html, h, keepWithNext = 0) => ({ type: 'block', html, h, keepWithNext });

const shareCell = (value, color) => `
  <td style="${TD}">
    <div style="display:flex;align-items:center;justify-content:flex-end;gap:7px;">
      <div style="width:46px;height:5px;border-radius:99px;background:#f1f5f9;overflow:hidden;flex-shrink:0;">
        <div style="width:${Math.max(2, Math.min(100, num(value)))}%;height:100%;background:${color};border-radius:99px;"></div>
      </div>
      <span style="font-size:9.5px;font-weight:700;color:${color};width:38px;text-align:right;">${pct(value)}</span>
    </div>
  </td>`;

const dotLabel = (text, color) => `<span style="display:inline-block;width:7px;height:7px;border-radius:2px;background:${color};margin-right:7px;"></span>${esc(text)}`;

// ── Page packer ─────────────────────────────────────────────────────────
// Each section starts on a fresh page (like the other reports' detail and
// closing pages) and flows onto as many pages as its content needs — except
// that a section joins the current page when that page is still mostly
// empty (e.g. it only holds the last row or two of the previous section's
// table), instead of leaving that page nearly blank.
const inlineHead = (sec) => `<div style="margin-top:34px;">${sec.head(false)}</div>`;
const INLINE_HEAD_H = 96;

// Room the first item of a section needs, so a section never starts with
// its heading alone at the bottom of a page.
function firstNeed(item) {
  if (!item) return 0;
  if (item.type === 'block') return item.h;
  const r = item.rows;
  if (!r.length) return item.titleH + item.headH + item.emptyH;
  return item.titleH + item.headH + r[0].h + (r[1] ? r[1].h : item.footH);
}

function paginate(sections, budget) {
  const pages = [];
  let page = null;
  let used = 0;
  sections.forEach((sec) => {
    const open = (continued) => {
      page = { head: sec.head(continued), parts: [] };
      used = continued ? (sec.headContH ?? sec.headH) : sec.headH;
      pages.push(page);
    };
    const fits = (h) => used + h <= budget;
    const inlineH = sec.inlineHeadH ?? INLINE_HEAD_H;
    if (page && used < budget / 2 && fits(inlineH + firstNeed(sec.items[0]))) {
      page.parts.push(inlineHead(sec));
      used += inlineH;
    } else {
      open(false);
    }

    sec.items.forEach((item) => {
      if (item.type === 'block') {
        if (!fits(item.h + item.keepWithNext) && page.parts.length) open(true);
        page.parts.push(item.html);
        used += item.h;
        return;
      }
      // table
      const { rows } = item;
      let i = 0;
      let first = true;
      do {
        const lead = item.titleH + item.headH;
        // A table only starts on this page if at least two of its rows (or
        // all of them, if fewer) fit under its header.
        const minRows = Math.min(2, rows.length - i);
        let minNeed = lead + (rows.length ? 0 : item.emptyH) + (rows.length - i <= minRows ? item.footH : 0);
        for (let k = 0; k < minRows; k++) minNeed += rows[i + k].h;
        if (!fits(minNeed) && page.parts.length) open(true);
        let h = lead;
        const chunk = [];
        while (i < rows.length) {
          const add = rows[i].h + (i === rows.length - 1 ? item.footH : 0);
          if (chunk.length && !fits(h + add)) break;
          chunk.push(rows[i].html);
          h += rows[i].h;
          i++;
        }
        // …and never carries a single last row over to the next page alone.
        if (i === rows.length - 1 && chunk.length >= 3) {
          chunk.pop();
          i--;
          h -= rows[i].h;
        }
        const done = i >= rows.length;
        if (done) h += rows.length ? item.footH : item.emptyH;
        page.parts.push(item.render({ rowsHtml: chunk.join(''), withFoot: done, continued: !first }));
        used += h;
        first = false;
        if (!done) open(true);
      } while (i < rows.length);
    });
  });
  return pages;
}

function sectionHead(title, caption) {
  return (continued) => `
    <div style="font-family:'Playfair Display',serif;font-size:22px;font-weight:700;color:#0f172a;letter-spacing:-0.4px;">${title}${continued ? ' <span style="font-family:\'DM Sans\',sans-serif;font-size:11px;font-weight:600;color:#94a3b8;letter-spacing:0;">(continued)</span>' : ''}</div>
    <div style="font-size:10.5px;color:#64748b;margin-top:4px;margin-bottom:6px;">${caption}</div>`;
}
const SECTION_HEAD_H = 62;

// ── Sections ────────────────────────────────────────────────────────────
function overviewSection(d) {
  const k = d.kpi || {};
  const who = [esc(d.clientName || d.title), d.isAll ? (d.memberCount > 2 ? 'All family members' : '') : esc(d.memberName)].filter(Boolean).join(' &nbsp;·&nbsp; ');
  const metaBits = [d.since ? `Investing since ${esc(d.since)}` : '', esc(d.meta)].filter(Boolean).join(' &nbsp;·&nbsp; ');

  const head = (continued) => continued
    ? sectionHead('Portfolio Overview', `${who}`)(true)
    : `
    <div style="font-family:'Playfair Display',serif;font-size:26px;font-weight:700;color:#0f172a;letter-spacing:-0.5px;">Portfolio Review Report</div>
    <div style="font-size:14px;font-weight:600;color:#475569;margin-top:7px;">${who}</div>
    ${metaBits ? `<div style="font-size:10px;color:#94a3b8;margin-top:4px;line-height:1.5;">${metaBits}</div>` : ''}
    <div style="padding-bottom:6px;border-bottom:1px solid #e2e8f0;"></div>`;
  const headH = 112 + (metaBits ? (lines(d.meta, 110) - 1) * 15 : 0);

  const items = [];
  const sipCaption = k.sipTotal ? `${k.sipCount || 0} mandate${k.sipCount === 1 ? '' : 's'} · 3rd month` : 'No active SIP';
  items.push(block(`
    ${subHeading('Portfolio at a glance')}
    <div style="display:flex;gap:8px;">
      ${kpiTile({ label: 'Total Invested', value: money(k.invested), caption: `${k.schemes || 0} scheme${k.schemes === 1 ? '' : 's'}`, accent: '#1d4ed8', bg: '#eff6ff' })}
      ${kpiTile({ label: 'Current Value', value: money(k.current), caption: `${num(k.gainPct) >= 0 ? '▲' : '▼'} ${Math.abs(num(k.gainPct)).toFixed(2)}% overall`, accent: '#047857', bg: '#ecfdf5' })}
      ${kpiTile({ label: 'Gain / Loss', value: `<span style="color:${gainHex(k.gain)}">${signedMoney(k.gain)}</span>`, caption: num(k.gain) >= 0 ? 'Profit to date' : 'Loss to date', accent: '#c2410c', bg: '#fff7ed' })}
      ${kpiTile({ label: 'Monthly SIP', value: k.sipTotal ? rupees(k.sipTotal) : '—', caption: sipCaption, accent: '#4338ca', bg: '#eef2ff' })}
      ${kpiTile({ label: 'XIRR / CAGR', value: `<span style="color:${num(k.xirr) >= 0 ? '#16a34a' : '#dc2626'}">${pct(k.xirr, 2)}</span>`, caption: 'Annualised return', accent: '#0e7490', bg: '#ecfeff' })}
    </div>`, SUB_HEADING_H + 96));

  // Asset class mix — CSS conic-gradient donut + legend, as in the Asset
  // Allocation report.
  const mix = [
    { name: 'Equity', value: num(d.assetMix?.eq) },
    { name: 'Debt', value: num(d.assetMix?.dt) },
    { name: 'Gold', value: num(d.assetMix?.gold) },
  ].filter(x => x.value > 0);
  const mixTotal = mix.reduce((s, x) => s + x.value, 0);
  let cursor = 0;
  const gradient = mix.length ? `conic-gradient(${mix.map((x) => {
    const start = cursor;
    cursor += (x.value / mixTotal) * 100;
    return `${ASSET_COLORS[x.name]} ${start}% ${cursor}%`;
  }).join(', ')})` : '#e2e8f0';
  const legend = mix.map(x => `
    <div style="margin-bottom:12px;">
      <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:5px;">
        <div style="display:flex;align-items:center;gap:7px;">
          <span style="width:9px;height:9px;border-radius:2px;background:${ASSET_COLORS[x.name]};display:inline-block;"></span>
          <span style="font-size:11px;font-weight:600;color:#334155;">${x.name}</span>
        </div>
        <div style="display:flex;align-items:center;gap:10px;">
          <span style="font-size:11px;font-weight:700;color:#0f172a;">${money((x.value / 100) * num(k.current))}</span>
          <span style="font-size:10px;font-weight:700;color:${ASSET_COLORS[x.name]};width:42px;text-align:right;display:inline-block;">${pct(x.value)}</span>
        </div>
      </div>
      <div style="height:5px;border-radius:99px;background:#f1f5f9;overflow:hidden;">
        <div style="width:${Math.max(1, Math.min(100, x.value))}%;height:100%;background:${ASSET_COLORS[x.name]};border-radius:99px;"></div>
      </div>
    </div>`).join('');
  items.push(block(`
    ${subHeading('Asset class mix')}
    <div style="border:1px solid #e2e8f0;border-radius:14px;padding:20px 22px;display:flex;align-items:center;gap:26px;">
      <div style="position:relative;width:132px;height:132px;flex-shrink:0;">
        <div style="width:132px;height:132px;border-radius:50%;background:${gradient};"></div>
        <div style="position:absolute;top:16px;left:16px;width:100px;height:100px;border-radius:50%;background:white;display:flex;flex-direction:column;align-items:center;justify-content:center;">
          <div style="font-size:8px;font-weight:700;letter-spacing:0.5px;text-transform:uppercase;color:#94a3b8;">Current Value</div>
          <div style="font-size:12px;font-weight:800;color:#0f172a;margin-top:3px;">${money(k.current)}</div>
        </div>
      </div>
      <div style="flex:1;min-width:0;">${legend || '<div style="font-size:11px;color:#94a3b8;font-style:italic;">No asset class split available for this statement.</div>'}</div>
    </div>`, SUB_HEADING_H + 176));

  const cats = (d.categories || []).filter(c => num(c.pct) > 0).sort((a, b) => num(b.pct) - num(a.pct));
  items.push(tableItem({
    title: 'Category breakdown',
    cols: [{ label: 'Category' }, { label: 'Share of portfolio', align: 'right', width: '42%' }],
    rows: cats.map((c, i) => ({
      h: 15 + lines(c.label, 60) * 14,
      html: `<tr><td style="${TD}font-weight:600;color:#0f172a;">${dotLabel(c.label, PALETTE[i % PALETTE.length])}</td>${shareCell(c.pct, PALETTE[i % PALETTE.length])}</tr>`,
    })),
    emptyText: 'No category split available for this statement.',
  }));

  return { head, headH, items };
}

function holdingsSection(d) {
  const holdings = d.holdings || [];
  const total = holdings.reduce((s, h) => s + num(h.current), 0) || 1;
  const rows = holdings.map((h) => {
    const g = num(h.current) - num(h.invested);
    const gp = num(h.invested) ? (g / num(h.invested)) * 100 : 0;
    const al = (num(h.current) / total) * 100;
    const b = BADGE[h.badge] || BADGE.go;
    const nameLines = lines(h.name, 30);
    const catLines = lines(h.cat, 15);
    return {
      h: Math.max(16 + nameLines * 14 + (h.holder ? 13 : 0), 20 + catLines * 12),
      html: `<tr>
        <td style="${TD}">
          <div style="font-size:10px;font-weight:700;color:#0f172a;line-height:1.4;">${esc(h.name || '—')}</div>
          ${h.holder ? `<div style="font-size:8.5px;color:#94a3b8;margin-top:1px;">Holder: ${esc(h.holder)}</div>` : ''}
        </td>
        <td style="${TD}"><span style="display:inline-block;font-size:8.5px;font-weight:700;color:${b.fg};background:${b.bg};padding:2px 7px;border-radius:99px;line-height:1.4;">${esc(h.cat || '—')}</span></td>
        <td style="${TD}text-align:right;white-space:nowrap;">${money(h.invested)}</td>
        <td style="${TD}text-align:right;white-space:nowrap;font-weight:700;color:#0f172a;">${money(h.current)}</td>
        <td style="${TD}text-align:right;white-space:nowrap;font-weight:700;color:${gainHex(g)};">${signedPct(gp)}</td>
        <td style="${TD}text-align:right;white-space:nowrap;font-weight:600;color:#475569;">${pct(al)}</td>
        <td style="${TD}text-align:right;white-space:nowrap;font-weight:700;color:${xirrHex(h.xirr)};">${pct(h.xirr, 2)}</td>
      </tr>`,
    };
  });
  const invested = holdings.reduce((s, h) => s + num(h.invested), 0);
  const current = holdings.reduce((s, h) => s + num(h.current), 0);
  const gainAll = invested ? ((current - invested) / invested) * 100 : 0;
  const foot = holdings.length ? `<tr>
    <td style="${TF}" colspan="2">Total · ${holdings.length} scheme${holdings.length === 1 ? '' : 's'}</td>
    <td style="${TF}text-align:right;white-space:nowrap;">${money(invested)}</td>
    <td style="${TF}text-align:right;white-space:nowrap;">${money(current)}</td>
    <td style="${TF}text-align:right;white-space:nowrap;color:${gainHex(gainAll)};">${signedPct(gainAll)}</td>
    <td style="${TF}text-align:right;">100%</td>
    <td style="${TF}"></td>
  </tr>` : '';

  // An individual member's own SIP mandates (the All Members view has the
  // consolidated SIP tables instead).
  const sips = d.isAll ? [] : (d.sips || []);
  const sipTotal = sips.reduce((s, x) => s + num(x.amount), 0);
  const sipItem = sips.length ? tableItem({
    title: 'Active SIPs',
    cols: [{ label: 'Fund' }, { label: 'SIP date', width: '20%' }, { label: 'Monthly SIP', align: 'right', width: '20%' }],
    rows: sips.map((s, i) => ({
      h: 16 + lines(s.name, 52) * 14,
      html: `<tr>
        <td style="${TD}font-weight:600;color:#0f172a;">${dotLabel(s.name, PALETTE[i % PALETTE.length])}</td>
        <td style="${TD}">Every month · ${esc(s.date || '—')}</td>
        <td style="${TD}text-align:right;white-space:nowrap;font-weight:700;color:#0f172a;">${rupees(s.amount)}</td>
      </tr>`,
    })),
    foot: `<tr><td style="${TF}" colspan="2">Total monthly SIP</td><td style="${TF}text-align:right;white-space:nowrap;color:#16a34a;">${rupees(sipTotal)}</td></tr>`,
  }) : null;

  return {
    head: sectionHead('Scheme Holdings', `Every scheme in ${d.isAll ? 'the portfolio' : `${esc(d.memberName)}'s portfolio`}, largest holding first`),
    headH: SECTION_HEAD_H,
    items: [tableItem({
      cols: [
        { label: 'Scheme', width: '31%' },
        { label: 'Category', width: '17%' },
        { label: 'Invested', align: 'right', width: '11.5%' },
        { label: 'Current', align: 'right', width: '11.5%' },
        { label: 'Gain', align: 'right', width: '9.5%' },
        { label: 'Alloc.', align: 'right', width: '9%' },
        { label: 'XIRR', align: 'right', width: '10.5%' },
      ],
      rows,
      foot,
      emptyText: 'No holdings found in this statement.',
    }), ...(sipItem ? [sipItem] : [])],
  };
}

function consolidatedSection(c) {
  const items = [];
  const amcRows = (c.amcAllocRows || []).map((r, i) => ({
    h: 16 + lines(r.amc, 34) * 14,
    html: `<tr>
      <td style="${TD}font-weight:600;color:#0f172a;">${dotLabel(r.amc, PALETTE[i % PALETTE.length])}</td>
      <td style="${TD}text-align:right;white-space:nowrap;">${money(r.invested)}</td>
      <td style="${TD}text-align:right;white-space:nowrap;font-weight:700;color:#0f172a;">${money(r.current)}</td>
      ${shareCell(r.allocation, PALETTE[i % PALETTE.length])}
    </tr>`,
  }));
  items.push(tableItem({
    title: 'AMC-wise allocation',
    cols: [{ label: 'AMC' }, { label: 'Invested', align: 'right', width: '18%' }, { label: 'Current', align: 'right', width: '18%' }, { label: 'Allocation', align: 'right', width: '24%' }],
    rows: amcRows,
    foot: amcRows.length ? `<tr><td style="${TF}">Total</td><td style="${TF}text-align:right;white-space:nowrap;">${money(c.amcAllocTotalInv)}</td><td style="${TF}text-align:right;white-space:nowrap;">${money(c.amcAllocTotalCur)}</td><td style="${TF}text-align:right;">100%</td></tr>` : '',
    emptyText: 'No AMC data available.',
  }));

  const subRows = (c.catRows || []).map((r, i) => {
    const gp = num(r.invested) ? ((num(r.current) - num(r.invested)) / num(r.invested)) * 100 : 0;
    return {
      h: 16 + lines(r.cat, 28) * 14,
      html: `<tr>
        <td style="${TD}font-weight:600;color:#0f172a;">${dotLabel(r.cat, PALETTE[i % PALETTE.length])}</td>
        <td style="${TD}text-align:right;white-space:nowrap;">${money(r.invested)}</td>
        <td style="${TD}text-align:right;white-space:nowrap;font-weight:700;color:#0f172a;">${money(r.current)}</td>
        <td style="${TD}text-align:right;white-space:nowrap;font-weight:700;color:${gainHex(gp)};">${signedPct(gp)}</td>
        ${shareCell(r.allocation, PALETTE[i % PALETTE.length])}
      </tr>`,
    };
  });
  const subGain = num(c.catTotalInv) ? ((num(c.catTotalCur) - num(c.catTotalInv)) / num(c.catTotalInv)) * 100 : null;
  items.push(tableItem({
    title: 'Sub-category breakdown',
    cols: [{ label: 'Sub-category' }, { label: 'Invested', align: 'right', width: '15%' }, { label: 'Current', align: 'right', width: '15%' }, { label: 'Gain', align: 'right', width: '11%' }, { label: 'Allocation', align: 'right', width: '22%' }],
    rows: subRows,
    foot: subRows.length ? `<tr><td style="${TF}">Total</td><td style="${TF}text-align:right;white-space:nowrap;">${money(c.catTotalInv)}</td><td style="${TF}text-align:right;white-space:nowrap;">${money(c.catTotalCur)}</td><td style="${TF}text-align:right;white-space:nowrap;${subGain === null ? '' : `color:${gainHex(subGain)};`}">${subGain === null ? '—' : signedPct(subGain)}</td><td style="${TF}text-align:right;">100%</td></tr>` : '',
    emptyText: 'No sub-category data available.',
  }));

  const sipTotal = num(c.sipTotal);
  const sipShare = (amt) => (sipTotal > 0 ? (num(amt) / sipTotal) * 100 : 0);
  const sipTable = (title, label, list, key, perLine) => {
    const rows = (list || []).map((r, i) => ({
      h: 16 + lines(r[key], perLine) * 14,
      html: `<tr>
        <td style="${TD}font-weight:600;color:#0f172a;">${dotLabel(r[key], PALETTE[i % PALETTE.length])}</td>
        <td style="${TD}text-align:right;white-space:nowrap;font-weight:700;color:#0f172a;">${rupees(r.amount)}</td>
        ${shareCell(sipShare(r.amount), PALETTE[i % PALETTE.length])}
      </tr>`,
    }));
    return tableItem({
      title,
      cols: [{ label }, { label: 'Monthly SIP', align: 'right', width: '20%' }, { label: 'Share', align: 'right', width: '24%' }],
      rows,
      foot: rows.length ? `<tr><td style="${TF}">Total monthly SIP</td><td style="${TF}text-align:right;white-space:nowrap;color:#16a34a;">${rupees(sipTotal)}</td><td style="${TF}text-align:right;">100%</td></tr>` : '',
      emptyText: 'No active SIP found.',
    });
  };
  items.push(sipTable('Consolidated SIP details', 'Fund', c.sipRows, 'name', 52));
  items.push(sipTable('Category-wise SIP allocation', 'Category', c.catSipRows, 'cat', 52));
  items.push(sipTable('AMC-wise SIP allocation', 'AMC', c.amcSipRows, 'amc', 52));

  return {
    head: sectionHead('Consolidated Overview', 'AMC, sub-category and SIP split across all family members'),
    headH: SECTION_HEAD_H,
    items,
  };
}

function notesSection(d) {
  const notes = d.alerts || [];
  const items = notes.map((a, i) => {
    const t = NOTE[a.type] || NOTE.info;
    const text = esc(a.text).replace(/\n+/g, '<br>');
    const h = 30 + lines(a.text, 95) * 16 + (String(a.text).match(/\n/g) || []).length * 16;
    return block(`
    <div style="display:flex;gap:12px;background:#f8fafc;border:1px solid #e2e8f0;border-left:3px solid ${t.color};border-radius:8px;padding:11px 14px;margin-top:${i === 0 ? 14 : 8}px;break-inside:avoid;page-break-inside:avoid;">
      <div style="font-size:10px;font-weight:800;color:${t.color};flex-shrink:0;width:18px;">${String(i + 1).padStart(2, '0')}</div>
      <div style="min-width:0;">
        <div style="display:inline-block;font-size:8px;font-weight:800;letter-spacing:0.6px;text-transform:uppercase;color:${t.color};background:${t.bg};padding:2px 7px;border-radius:99px;margin-bottom:5px;">${t.label}</div>
        <div style="font-size:10.5px;color:#334155;line-height:1.55;">${text}</div>
      </div>
    </div>`, h);
  });
  if (!items.length) {
    items.push(block('<div style="margin-top:14px;font-size:11px;color:#94a3b8;font-style:italic;">No advisory notes for this portfolio.</div>', 40));
  }
  items.push(block(`<div style="font-size:8.5px;color:#94a3b8;font-style:italic;margin-top:18px;line-height:1.5;">Important: Figures are as extracted from the client's consolidated statement${d.statementNote ? ` (${esc(d.statementNote)})` : ''} and may not reflect later market movements. Mutual fund investments are subject to market risks; past returns do not guarantee future performance. Please review the latest statement with your advisor before acting on any recommendation.</div>`, 64));
  return {
    head: sectionHead('Advisory Notes', 'Observations and recommendations from this review'),
    headH: SECTION_HEAD_H,
    items,
  };
}

// The fonts the report is printed in — measured with the same ones.
export const PORTFOLIO_REPORT_FONTS = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700&family=DM+Sans:wght@400;500;600;700;800&display=swap';

const reportDate = () => new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

function buildSections(data) {
  const sections = [overviewSection(data), holdingsSection(data)];
  if (data.isAll && data.consol) sections.push(consolidatedSection(data.consol));
  sections.push(notesSection(data));
  return sections;
}

function renderPages(sections, dateStr, budget) {
  const pages = paginate(sections, budget);
  return pages.map((p, i) => `${pageOpen()}
    ${letterheadHtml(dateStr)}
    ${p.head}
    ${p.parts.join('')}
    ${footerHtml(i + 1, pages.length)}
  ${pageClose()}`).join('');
}

const withTimeout = (promise, ms) => Promise.race([promise, new Promise((r) => setTimeout(r, ms))]);

// Measures every piece of the report at its printed width, in its printed
// fonts, inside a hidden iframe (its own document, so the fonts it loads
// never touch the app), and replaces the height estimates with the real
// heights. Returns the room left on a page between letterhead and footer.
async function measure(sections, dateStr) {
  const iframe = document.createElement('iframe');
  iframe.setAttribute('aria-hidden', 'true');
  iframe.tabIndex = -1;
  iframe.style.cssText = 'position:fixed;left:-12000px;top:0;width:900px;height:1200px;border:0;visibility:hidden;pointer-events:none;';
  document.body.appendChild(iframe);
  try {
    const doc = iframe.contentDocument;
    const loaded = new Promise((resolve) => { iframe.onload = resolve; });
    doc.open();
    doc.write(`<!DOCTYPE html><html><head><meta charset="UTF-8"><link href="${PORTFOLIO_REPORT_FONTS}" rel="stylesheet"><style>*{box-sizing:border-box}html,body{margin:0;padding:0}</style></head><body></body></html>`);
    doc.close();
    await withTimeout(loaded, 4000);
    await withTimeout(Promise.all([
      ...[400, 500, 600, 700, 800].map((w) => doc.fonts.load(`${w} 12px "DM Sans"`)),
      doc.fonts.load('700 22px "Playfair Display"'),
    ]).catch(() => {}), 4000);

    // Same box as a report page: fixed width, flex column (so margins add
    // up exactly as they do on the page — flex items' margins don't collapse).
    const box = doc.createElement('div');
    box.style.cssText = `width:${PAGE_W}px;display:flex;flex-direction:column;font-family:'DM Sans',system-ui,sans-serif;color:#1e293b;`;
    doc.body.appendChild(box);
    const heightOf = (html) => { box.innerHTML = html; return box.getBoundingClientRect().height; };

    const letterhead = heightOf(letterheadHtml(dateStr));
    const footer = heightOf(footerHtml(88, 88));
    sections.forEach((sec) => {
      sec.headH = heightOf(sec.head(false));
      sec.headContH = heightOf(sec.head(true));
      sec.inlineHeadH = heightOf(inlineHead(sec));
      sec.items.forEach((item) => {
        if (item.type === 'block') { item.h = heightOf(item.html); return; }
        box.innerHTML = item.render({ rowsHtml: item.rows.map((r) => r.html).join(''), withFoot: true, continued: false });
        const frame = box.querySelector('[data-table-frame]');
        const table = frame.querySelector('table');
        const frameRect = frame.getBoundingClientRect();
        item.titleH = frameRect.top - box.getBoundingClientRect().top;
        item.headH = table.tHead.getBoundingClientRect().height + (frameRect.height - table.getBoundingClientRect().height);
        const trs = table.tBodies[0].rows;
        if (item.rows.length) item.rows.forEach((r, i) => { r.h = trs[i].getBoundingClientRect().height; });
        else item.emptyH = trs[0].getBoundingClientRect().height;
        item.footH = table.tFoot ? table.tFoot.getBoundingClientRect().height : 0;
      });
    });
    // A few px of slack so rounding can never push a footer over the edge.
    return PAGE_MIN_H - letterhead - footer - 6;
  } finally {
    iframe.remove();
  }
}

// The report as print-ready HTML pages, laid out from measured heights (or
// from the estimates if measuring fails for any reason).
export async function layoutPortfolioReport(data) {
  const dateStr = reportDate();
  const sections = buildSections(data);
  let budget = BODY_BUDGET;
  try {
    budget = await measure(sections, dateStr);
  } catch {
    // estimates already in place
  }
  return renderPages(sections, dateStr, budget);
}
