// Top Performing Schemes — workbook importer + screening engine.
//
// Everything here is PURE: it takes an uploaded workbook's bytes and returns
// plain objects. No network, no React, no DOM. That keeps the risky part (the
// part that has to cope with whatever Excel file arrives next month) isolated
// and independently checkable.
//
// ---------------------------------------------------------------------------
// The two representations, and why they are kept apart
// ---------------------------------------------------------------------------
// RAW      — `headers` + `rawRows` are the worksheet exactly as uploaded, as
//            the display strings Excel itself shows. Nothing is reordered,
//            renamed, recalculated or dropped. Rendered by "Uploaded Data".
// ANALYSIS — `schemes` are SYSTEM-GENERATED by the screening rule below.
//            Derived, recomputable, and never written back over the raw rows.
//
// ---------------------------------------------------------------------------
// The screening rule
// ---------------------------------------------------------------------------
//   Median >  Average Median  →  TOP_PERFORMING
//   Median <= Average Median  →  BELOW_THRESHOLD
//   either value missing      →  NOT_AVAILABLE
//
// NOT_AVAILABLE is a real, first-class outcome, not an error state. If a
// worksheet carries no Average Median, screening simply does not run for that
// category — a value is never assumed, defaulted or back-filled, and the raw
// data is still imported and displayed in full.
//
// ---------------------------------------------------------------------------
// Why detection is heuristic AND overridable
// ---------------------------------------------------------------------------
// Next month's workbook may have more or fewer sheets, extra columns, a
// different header position or a renamed "Median" column. So the layout of
// each sheet is DETECTED rather than hard-coded — and every detected choice
// (header row, scheme column, median column, average median) is returned as a
// plain field the upload UI shows and lets the user correct before saving.
// Detection getting it wrong is therefore a two-click fix, never a code change.
import * as XLSX from 'xlsx';

export const RESULT = {
  TOP: 'TOP_PERFORMING',
  BELOW: 'BELOW_THRESHOLD',
  NA: 'NOT_AVAILABLE',
};

export const RESULT_LABEL = {
  [RESULT.TOP]: 'Top Performing',
  // Deliberately not "poor"/"bad": this is the outcome of one screening
  // methodology, not a judgement about the fund itself.
  [RESULT.BELOW]: 'Below Screening Threshold',
  [RESULT.NA]: 'Screening Not Available',
};

const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'];

// "2026-09" → "September 2026". Anything unparseable is echoed back as-is so a
// malformed key can never render as "undefined NaN".
export function monthLabel(key) {
  const m = /^(\d{4})-(\d{2})$/.exec(String(key || ''));
  if (!m) return String(key || '—');
  const idx = Number(m[2]) - 1;
  return MONTH_NAMES[idx] ? `${MONTH_NAMES[idx]} ${m[1]}` : key;
}

export const monthKey = (year, monthIndex0) =>
  `${year}-${String(monthIndex0 + 1).padStart(2, '0')}`;

// ---------------------------------------------------------------------------
// Cell value helpers
// ---------------------------------------------------------------------------

const txt = (v) => (v == null ? '' : String(v).trim());

// A cell counts as a number only if the WHOLE cell is numeric-looking. This
// matters: a bare /\d+/ extraction would happily read "ICICI Pru Nifty 50" as
// the number 50 and quietly screen a scheme on its own name.
//
// Accepts: 19.59 · "19.59" · "19.59%" · "1,234.5" · "(2.31)" (accounting
// negative) · "  -4.2 % ". Rejects: "" · "-" · "NA" · "N.A." · any label.
const NUMERIC_RE = /^[-+]?\(?\s*[\d,]*\.?\d+\s*\)?\s*%?$/;

export function parseNumber(v) {
  if (v == null || v === '') return null;
  if (typeof v === 'number') return Number.isFinite(v) ? v : null;
  const s = String(v).trim();
  if (!s || !NUMERIC_RE.test(s)) return null;
  const negative = /^\(.*\)$/.test(s.replace(/[%\s]/g, '')) || s.startsWith('-');
  const digits = s.replace(/[(),%\s+-]/g, '');
  if (!digits) return null;
  const n = Number(digits);
  if (!Number.isFinite(n)) return null;
  return negative ? -n : n;
}

export const isNumericCell = (v) => parseNumber(v) !== null;

// ---------------------------------------------------------------------------
// Header / column detection
// ---------------------------------------------------------------------------

const SCHEME_HEADER_RE = /scheme|fund\s*name|^\s*name\s*$|particular/i;
const MEDIAN_RE = /median/i;
const AVG_RE = /\b(avg|average)\b|averge|avarage/i; // common misspellings included
const PERF_HEADER_RE = /median|return|cagr|\byr\b|year|month|rank|quartile|aum|nav|ratio|alpha|beta|%/i;

// Rows that are category summaries / footers rather than schemes. These are
// excluded from the ANALYSIS rows (they are not schemes) but remain fully
// present in the raw view, which shows the sheet verbatim.
const SUMMARY_ROW_RE = /^\s*(average|avg|median|total|grand\s*total|category\s*(average|avg)|overall)\b/i;

/**
 * Picks the row most likely to be the header row.
 * Workbooks routinely carry a title row, a blank row, maybe an "as on <date>"
 * line before the real headers, so the header is rarely row 0.
 */
export function detectHeaderRow(aoa) {
  let best = { index: 0, score: -Infinity };
  const limit = Math.min(aoa.length, 25);

  for (let i = 0; i < limit; i++) {
    const row = aoa[i] || [];
    const cells = row.map(txt);
    const nonEmpty = cells.filter(Boolean);
    if (nonEmpty.length < 2) continue;

    let score = 0;
    if (nonEmpty.some((c) => SCHEME_HEADER_RE.test(c))) score += 6;
    if (nonEmpty.some((c) => MEDIAN_RE.test(c))) score += 4;
    if (nonEmpty.filter((c) => PERF_HEADER_RE.test(c)).length >= 3) score += 3;
    score += Math.min(nonEmpty.length, 12) * 0.25;

    // A row that is mostly numbers is data, not headers.
    const numeric = nonEmpty.filter(isNumericCell).length;
    if (numeric >= nonEmpty.length / 2) score -= 8;

    // Prefer the earliest strong candidate — a later row can score the same by
    // accident (e.g. a repeated header band partway down a long sheet).
    if (score > best.score) best = { index: i, score };
  }
  return best.score === -Infinity ? 0 : best.index;
}

// Header labels, normalised for display only. Blank header cells become
// "Column N" so a column with no title is still addressable in the UI — the
// underlying raw cells for that column are untouched.
export function normalizeHeaders(headerRow, width) {
  const out = [];
  for (let i = 0; i < width; i++) {
    const h = txt(headerRow?.[i]);
    out.push(h || `Column ${i + 1}`);
  }
  return out;
}

export function detectSchemeCol(headers, dataRows) {
  // 1. An explicit "Scheme Name" / "Fund Name" header.
  let idx = headers.findIndex((h) => /scheme\s*name|fund\s*name/i.test(h));
  if (idx >= 0) return idx;
  // 2. Any scheme-ish header.
  idx = headers.findIndex((h) => SCHEME_HEADER_RE.test(h));
  if (idx >= 0) return idx;
  // 3. Otherwise the first column that actually looks like text labels.
  for (let c = 0; c < headers.length; c++) {
    const vals = dataRows.map((r) => txt(r?.[c])).filter(Boolean);
    if (vals.length < 2) continue;
    const textish = vals.filter((v) => !isNumericCell(v)).length;
    if (textish / vals.length > 0.6) return c;
  }
  return headers.length ? 0 : null;
}

export function detectMedianCol(headers) {
  // Exact "Median" wins over anything merely containing it.
  let idx = headers.findIndex((h) => /^\s*median\s*$/i.test(h));
  if (idx >= 0) return idx;
  // Then any median column that is NOT the average-median column.
  idx = headers.findIndex((h) => MEDIAN_RE.test(h) && !AVG_RE.test(h));
  return idx >= 0 ? idx : null;
}

export function detectAvgMedianCol(headers) {
  const idx = headers.findIndex((h) => MEDIAN_RE.test(h) && AVG_RE.test(h));
  return idx >= 0 ? idx : null;
}

/**
 * Finds the category's single Average Median value.
 *
 * Workbooks express it in one of two shapes, so both are handled:
 *   (a) a dedicated "Average Median" COLUMN (usually the same value repeated,
 *       or filled in on the first row only), or
 *   (b) a LABELLED CELL somewhere on the sheet — typically a footer row like
 *       `Average Median | 12.20` or a header block above the table.
 *
 * Returns { value, source } where `source` is a plain-English note on where the
 * number came from, so the figure is auditable in the UI rather than magic.
 * Returns { value: null } when the sheet genuinely has no Average Median —
 * which is a valid outcome, never a guess.
 */
export function detectAvgMedian(aoa, headers, headerRowIndex) {
  // (a) A dedicated column.
  const col = detectAvgMedianCol(headers);
  if (col != null) {
    for (let r = headerRowIndex + 1; r < aoa.length; r++) {
      const n = parseNumber(aoa[r]?.[col]);
      if (n !== null) {
        return { value: n, source: `Column "${headers[col]}"`, col };
      }
    }
  }

  // (b) A labelled cell anywhere on the sheet — scanned last so an explicit
  // column always wins. Matches "Average Median", "Avg. Median",
  // "Average of Median", "Median Average", with any punctuation between.
  const LABEL_RE = /(average|avg|averge|avarage)[^a-z0-9]{0,6}(of[^a-z0-9]{0,3})?median|median[^a-z0-9]{0,6}(average|avg)/i;
  for (let r = 0; r < aoa.length; r++) {
    const row = aoa[r] || [];
    for (let c = 0; c < row.length; c++) {
      const cell = txt(row[c]);
      if (!cell || !LABEL_RE.test(cell)) continue;

      // The number usually sits to the right on the same row…
      for (let k = c + 1; k < row.length; k++) {
        const n = parseNumber(row[k]);
        if (n !== null) {
          return { value: n, source: `Cell labelled "${cell}" (row ${r + 1})`, col: null };
        }
      }
      // …or directly beneath the label.
      for (let k = r + 1; k < Math.min(r + 4, aoa.length); k++) {
        const n = parseNumber(aoa[k]?.[c]);
        if (n !== null) {
          return { value: n, source: `Cell below "${cell}" (row ${k + 1})`, col: null };
        }
      }
    }
  }

  return { value: null, source: null, col: null };
}

// ---------------------------------------------------------------------------
// Screening
// ---------------------------------------------------------------------------

/**
 * Applies Median > Average Median across one category's rows.
 * Pure and recomputable — call it again whenever the user corrects a detected
 * column or types in an Average Median the sheet did not carry.
 */
export function screenCategory({ rawRows, schemeCol, medianCol, avgMedian }) {
  const avg = typeof avgMedian === 'number' && Number.isFinite(avgMedian) ? avgMedian : null;

  return (rawRows || []).map((row, i) => {
    const schemeName = schemeCol == null ? '' : txt(row?.[schemeCol]);
    const median = medianCol == null ? null : parseNumber(row?.[medianCol]);

    let result = RESULT.NA;
    let difference = null;
    if (avg !== null && median !== null) {
      difference = Number((median - avg).toFixed(4));
      result = median > avg ? RESULT.TOP : RESULT.BELOW;
    }
    return { schemeName, median, avgMedian: avg, difference, result, rowIndex: i };
  }).filter((s) => s.schemeName); // a row with no scheme name is not a scheme
}

export function summarize(schemes) {
  const s = { total: schemes.length, top: 0, below: 0, na: 0 };
  for (const x of schemes) {
    if (x.result === RESULT.TOP) s.top++;
    else if (x.result === RESULT.BELOW) s.below++;
    else s.na++;
  }
  return s;
}

// ---------------------------------------------------------------------------
// Reporting-month detection
// ---------------------------------------------------------------------------

const MONTH_RE = new RegExp(
  `\\b(${MONTH_NAMES.join('|')}|jan|feb|mar|apr|jun|jul|aug|sep|sept|oct|nov|dec)\\b[^a-z0-9]{0,4}(\\d{4}|\\d{2})?`,
  'i'
);

function monthIndexFrom(word) {
  const w = word.toLowerCase();
  const i = MONTH_NAMES.findIndex((m) => m.toLowerCase() === w);
  if (i >= 0) return i;
  const short = w.slice(0, 3);
  return MONTH_NAMES.findIndex((m) => m.toLowerCase().startsWith(short));
}

function resolveMonth(word, yearRaw, now) {
  const mi = monthIndexFrom(word);
  if (mi < 0) return null;
  let year;
  if (yearRaw) {
    year = Number(yearRaw.length === 2 ? `20${yearRaw}` : yearRaw);
  } else {
    // No year given ("…- September.xlsx"). Take the most recent occurrence of
    // that month that is not in the future — a September file uploaded in
    // October 2026 means September 2026, not September 2027.
    year = now.getFullYear();
    if (mi > now.getMonth()) year -= 1;
  }
  if (!Number.isFinite(year) || year < 2000 || year > 2100) return null;
  return monthKey(year, mi);
}

/**
 * Best-effort "which month does this workbook describe?".
 * Looks at the file name first (the convention in use — "Scheme Performance
 * List - September.xlsx"), then any date-ish text near the top of the first
 * sheet. Returns null when it genuinely cannot tell, in which case the upload
 * UI asks the user to pick the month rather than guessing one.
 */
export function detectReportingMonth(fileName, sheets, now = new Date()) {
  const fromName = MONTH_RE.exec(String(fileName || ''));
  if (fromName) {
    const key = resolveMonth(fromName[1], fromName[2], now);
    if (key) return { key, source: 'file name' };
  }

  for (const sheet of (sheets || []).slice(0, 3)) {
    const head = (sheet.aoa || []).slice(0, 8);
    for (const row of head) {
      for (const cell of row || []) {
        const s = txt(cell);
        if (!s || s.length > 60) continue;
        const m = MONTH_RE.exec(s);
        if (!m) continue;
        const key = resolveMonth(m[1], m[2], now);
        if (key) return { key, source: `sheet "${sheet.name}"` };
      }
    }
  }
  return { key: null, source: null };
}

// ---------------------------------------------------------------------------
// Workbook entry point
// ---------------------------------------------------------------------------

/**
 * Reads every worksheet in the workbook and returns one descriptor per sheet.
 *
 * Sheet count and names are whatever the file contains — nothing is hard-coded
 * and nothing is skipped, so a workbook that gains or loses categories next
 * month imports correctly with no code change.
 *
 * `raw: false` is deliberate: it yields the FORMATTED display strings Excel
 * shows ("19.59%"), which is both what the raw view must reproduce and what
 * parseNumber can read back correctly. With `raw: true` a percent-formatted
 * cell arrives as 0.1959 and would render as a wrong-looking number.
 */
export function parseWorkbook(arrayBuffer, fileName, now = new Date()) {
  const wb = XLSX.read(arrayBuffer, { type: 'array', cellDates: true });
  const sheets = [];

  wb.SheetNames.forEach((name, sheetIndex) => {
    const ws = wb.Sheets[name];
    if (!ws) return;

    // `blankrows: true` keeps the array index of every row equal to its real
    // position in the sheet, so `headerRowIndex` and the "row N" note in
    // avgMedianSource line up with the row numbers the user sees in Excel.
    // Blank rows are dropped later, when building the displayable rawRows.
    const aoa = XLSX.utils.sheet_to_json(ws, {
      header: 1,
      defval: '',
      blankrows: true,
      raw: false,
    }).map((row) => (Array.isArray(row) ? row.map((c) => (c == null ? '' : String(c))) : []));

    // A sheet with nothing on it is still reported (so the user can see it was
    // present in the file) but carries no rows to analyse.
    if (!aoa.some((r) => r.some((c) => txt(c)))) {
      sheets.push({
        name, sheetIndex, aoa: [], headerRowIndex: 0, headers: [], rawRows: [],
        schemeCol: null, medianCol: null, avgMedian: null, avgMedianSource: null,
        empty: true,
      });
      return;
    }

    const headerRowIndex = detectHeaderRow(aoa);
    const width = aoa.reduce((w, r) => Math.max(w, r.length), 0);
    const headers = normalizeHeaders(aoa[headerRowIndex], width);

    // Every row below the header, padded to a uniform width so the raw table
    // renders as a clean grid. Summary/footer rows are kept here (raw must be
    // verbatim) and excluded from analysis further down.
    const allBelow = aoa.slice(headerRowIndex + 1)
      .map((r) => Array.from({ length: width }, (_, i) => (r?.[i] == null ? '' : String(r[i]))))
      .filter((r) => r.some((c) => txt(c)));

    const schemeCol = detectSchemeCol(headers, allBelow);
    const medianCol = detectMedianCol(headers);
    const avg = detectAvgMedian(aoa, headers, headerRowIndex);

    sheets.push({
      name,
      sheetIndex,
      aoa,
      headerRowIndex,
      headers,
      rawRows: allBelow,
      schemeCol,
      medianCol,
      avgMedian: avg.value,
      avgMedianSource: avg.source,
      empty: false,
    });
  });

  const month = detectReportingMonth(fileName, sheets, now);
  return { sheets, detectedMonth: month.key, monthSource: month.source };
}

/**
 * Rows that should be ANALYSED, as opposed to merely displayed. Drops the
 * category's own summary/footer lines ("Average Median", "Total", …), which
 * are not schemes — they stay visible in the raw view regardless.
 */
export function analysisRows(sheet) {
  if (sheet.schemeCol == null) return [];
  return (sheet.rawRows || []).filter((r) => {
    const label = txt(r[sheet.schemeCol]);
    return label && !SUMMARY_ROW_RE.test(label);
  });
}

/**
 * Turns a parsed + reviewed sheet into the payload the API stores: the raw
 * worksheet verbatim, plus the derived analysis rows alongside it.
 */
export function buildCategoryPayload(sheet, reportingMonth) {
  const rows = analysisRows(sheet);
  const schemes = screenCategory({
    rawRows: rows,
    schemeCol: sheet.schemeCol,
    medianCol: sheet.medianCol,
    avgMedian: sheet.avgMedian,
  });
  return {
    name: sheet.name,
    sheetIndex: sheet.sheetIndex,
    avgMedian: sheet.avgMedian,
    avgMedianSource: sheet.avgMedianSource,
    rawHeaders: sheet.headers,
    rawRows: sheet.rawRows,
    headerRowIndex: sheet.headerRowIndex,
    schemeCol: sheet.schemeCol,
    medianCol: sheet.medianCol,
    schemes: schemes.map((s) => ({ ...s, reportingMonth, categoryName: sheet.name })),
  };
}

// Display helper — a percentage that keeps two decimals and never prints
// "NaN%" / "null%" for a genuinely missing value.
export const pct = (v, digits = 2) =>
  v === null || v === undefined || !Number.isFinite(Number(v))
    ? '—'
    : `${Number(v).toFixed(digits)}%`;

export const signedPct = (v, digits = 2) =>
  v === null || v === undefined || !Number.isFinite(Number(v))
    ? '—'
    : `${Number(v) > 0 ? '+' : ''}${Number(v).toFixed(digits)}%`;
